"""도메인이 의존하는 추상 포트. 구체 구현(llm/)이 이걸 구현한다."""
from typing import Protocol

class RankerGateway(Protocol):
    def rank_candidates(self, question: str, candidate_ids: list) -> dict:
        """candidate_ids에 대한 {id: 'relevant'|'irrelevant'|'uncertain'} 반환."""
        ...


class GeneratorGateway(Protocol):
    def generate(self, prompt: str) -> str:
        """최종 프롬프트로 개인화 답변 텍스트 생성."""
        ...


class Repository(Protocol):
    """저장소 포트. SQLite/InMemory/Postgres/Supabase 어댑터가 이 계약을 구현한다.
    ApplicationService는 이 인터페이스에만 의존한다 (구체 DB를 모른다)."""
    def create_profile(self, user_id: str, profile) -> None: ...
    def list_profiles(self, user_id: str) -> list: ...
    def get_active_profile(self, user_id: str): ...
    def set_active_profile(self, user_id: str, profile_id: str) -> None: ...
    def update_profile(self, user_id: str, profile_id: str,
                       name: str, description: str) -> None: ...
    def delete_profile(self, user_id: str, profile_id: str) -> None: ...
    def save_profile_items(self, user_id: str, items: list,
                           profile_id: str | None = None) -> None: ...
    def load_profile_items(self, user_id: str,
                           profile_id: str | None = None) -> list: ...
    def save_interaction(self, interaction_id: str, user_id: str,
                         question: str, intent: str, state: str) -> None: ...
    def update_state(self, interaction_id: str, state: str) -> None: ...
    def save_answer(self, interaction_id: str, answer: str) -> None: ...
    def load_interaction(self, interaction_id: str) -> dict | None: ...
    def list_interactions(self, user_id: str) -> list: ...
    def save_snapshot(self, snapshot) -> None: ...
    def load_snapshot(self, interaction_id: str): ...
